### ISSUE TITLE
A possible misrepresentation in MultiLayerPerceptron

### ISSUE THREAD

**Issue by Adithya-Ramachandran** [ImagineAILab/ai-by-hand-excel#5]
Hello,

In Multi-Layer Perceptron.xlsx, small, Cell B31 indicates nn.Linear(4, 3), as in, the linear layer gets 4 input features and 3 output features. But the Matrices are represented for nn.Layer(3, 1). The output from the previous layer also has only 3 features. Please look into it and let me know if I am missing something.

![image](https://github.com/user-attachments/assets/f821acc0-52b5-405e-a1d0-9b68e5d1108a)

**Comment by doubleshow** [comment]
Thank you for reporting out this error! 
I'm glad you really studied this.

**Comment by 00JIMMY00** [comment]
![Capturooe](https://github.com/user-attachments/assets/8e6d4fbc-ecb1-412b-9a3d-478d88f6e43d)

Hello Tom Yeh , 
Thanks for your amazing excel ,
I think there is mistake here as no. of features is 2 and the input neurons are 4 ,
If I'm wrong correct me , 
I asked gpt-4 and here's the answer : 
From the setup, it looks like the diagram might be misinterpreted or incorrectly labeled if it suggests that the number of neurons in the input layer has increased due to the batch size. The actual number of neurons in the input layer should still match the number of features, which is 2, not 4. If the diagram is meant to illustrate multiple samples being processed, then it could make sense in a contextual visualization but should clarify that the number of neurons does not increase with the batch size.

**Comment by doubleshow** [comment]
Each input is a column vector. Each column vector has four features. Each feature is fed to one neuron. That's why we have four neurons at the input layer. I hope this clarifies.

**Comment by 00JIMMY00** [comment]
Thanks I got it.
